services:
  - type: web
    name: asubeb-backend
    env: node
    plan: starter
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build:render
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
    healthCheckPath: /api/v1/health
    autoDeploy: true
